proxy-providers:
  ID:
    type: file
    path: ./proxy_provider/id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  MIX:
    type: file
    path: ./proxy_provider/mix.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '100'
  DIRECTMODEM:
    type: file
    path: ./proxy_provider/directmodem.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: '50'
proxy-groups:
- name: Auto-ID_MIX
  type: fallback
  disable-udp: false
  use:
  - ID
  - MIX
  url: http://www.gstatic.com/generate_204
  interval: '100'
- name: Load-MIX_ID
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - MIX
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '100'
- name: Server-UMUM
  type: select
  disable-udp: false
  proxies:
  - Load-MIX_ID
  - Auto-ID_MIX
- name: Server-INDO
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
  use:
  - DIRECTMODEM
- name: Server-GAME
  type: select
  disable-udp: false
  proxies:
  - Auto-ID_MIX
  - DIRECT
  use:
  - DIRECTMODEM
- name: IKLAN
  type: select
  disable-udp: false
  proxies:
  - Server-UMUM
  - REJECT
rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./rule_provider/game.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_provider/umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./rule_provider/indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./rule_provider/sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./rule_provider/streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./rule_provider/bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./rule_provider/tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./rule_provider/meta.yaml
rules:
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,TCP)),Server-GAME
- AND,((NOT,((RULE-SET,Umum))),(NETWORK,UDP)),Server-GAME
- RULE-SET,Game,Server-GAME
- RULE-SET,indo,Server-INDO
- RULE-SET,Sosmed,Server-INDO
- RULE-SET,Streaming,Server-UMUM
- RULE-SET,Bankid,Server-INDO
- RULE-SET,Tiktok,Server-UMUM
- RULE-SET,Meta,Server-INDO
- MATCH,Server-UMUM
dns:
  proxy-server-nameserver:
    - dhcp://"eth1" # Sesuaikan dengan Modemmu
    - 192.168.42.129 # Sesuaikan Ip Modemmu
  nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - https://dns.google.com/dns-query
ntp:
  servers:
    - pool.ntp.org
    - id.pool.ntp.org
    - time.google.com